module.exports = {

// Australia
    'AU-ACT': 'Australian Capital Territory',
    'ACT': 'Australian Capital Territory',
    'NSW': 'New South Wales',
    'AU-NT': 'Northern Territory',
    'QLD': 'Queensland',
    'Queensland': 'Queensland',
    'SA': 'South Australia',
    'TAS': 'Tasmania',
    'VIC': 'Victoria',
    'Victoria': 'Victoria',
    'AU-WA': 'Western Australia', // Same Code as Washington

// Austria
    'Burgenland': 'Burgenland',
    'Kärnten': 'Kärnten',
    'Niederösterreich': 'Niederösterreich',
    'Salzburg': 'Salzburg',
    'Steiermark': 'Steiermark',
    'Tirol': 'Tirol',
    'Oberösterreich': 'Oberösterreich',
    'wien ': 'Vienna',
    'Vorarlberg': 'Vorarlberg',


// Canada
    'AB': 'Alberta',
    'BC': 'British Columbia',
    'MB': 'Manitoba',
    'NB': 'New Brunswick',
    'NL': 'Newfoundland and Labrador',
    'NT': 'Northwest Territories',
    'NS': 'Nova Scotia',
    'NU': 'Nunavut',
    'ON': 'Ontario',
    'PEI': 'Prince Edward Island',
    'QC': 'Quebec',
    'SK': 'Saskatchewan',
    'YU': 'Yukon',

// Canada
    'Auvergne-Rhône-Alpes': 'Auvergne-Rhône-Alpes',
    'Bourgogne-Franche-Comté': 'Bourgogne-Franche-Comté',
    'Bretagne': 'Bretagne',
    'Centre-Val de Loire': 'Centre-Val de Loire',
    'Corse': 'Corse',
    'Grand Est': 'Grand Est',
    'Guadeloupe': 'Guadeloupe',
    'Guyane': 'Guyane',
    'Île-de-France': 'Île-de-France',
    'La Réunion': 'La Réunion',
    'Martinique': 'Martinique',
    'Uritte': 'Uritte',
    'Normandie': 'Normandie',
    'Nouvelle-Aquitaine': 'Nouvelle-Aquitaine',
    'Occitanie': 'Occitanie',
    'Pays de la Loire': 'Pays de la Loire',
    'Île-de-France': 'Île-de-France',
    'Provence-Alpes-Côte d\'Azur ': 'Provence-Alpes-Côte d\'Azur',

// Germany
    'BW': 'Baden-Württemberg',
    'Baden-WÃ¼rttemberg': 'Baden-Württemberg',
    'BY': 'Bayern',
    'BE': 'Berlin',
    'Berlin': 'Berlin',
    'BB': 'Brandenburg',
    'HB': 'Bremen',
    'HH': 'Hamburg',
    'HE': 'Hessen',
    'NI': 'Niedersachsen',
    'MV': 'Mecklenburg-Vorpommern',
    'NW': 'Nordrhein-Westfalen',
    'RP': 'Rheinland-Pfalz',
    'SL': 'Saarland',
    'SN': 'Sachsen',
    'ST': 'Sachsen-Anhalt',

// Greece
    'Attica': 'Attica',
    'Athens': 'Attica',
    'Central Greece': 'Central Greece',
    'Central Macedonia': 'Central Macedonia',
    'Crete': 'Crete',
    'Berlin': 'Berlin',
    'Eastern Macedonia and Thrace': 'Eastern Macedonia and Thrace',
    'Epirus': 'Epirus',
    'Ionian Islands': 'Ionian Islands',
    'North Aegean': 'North Aegean',
    'Peloponnese': 'Peloponnese',
    'South Aegean': 'South Aegean',
    'Thessaly': 'Thessaly',
    'Western Greece': 'Western Greece',
    'Western Macedonia': 'Western Macedonia',

// Ireland
    'Antrim': 'Antrim',
    'Armagh': 'Armagh',
    'Carlow': 'Carlow',
    'Basel-Landschaft': 'Basel-Landschaft',
    'Clare': 'Clare',
    'Basel-Stadt': 'Basel-Stadt',
    'Bern': 'Bern',
    'Fribourg': 'Fribourg',
    'Geneva': 'Geneva',
    'Glarus': 'Glarus',
    'Jura': 'Jura',
    'Luzern': 'Luzern',
    'Neuchâtel': 'Neuchâtel',
    'Nidwalden': 'Nidwalden',
    'Obwalden': 'Obwalden',
    'Schaffhausen': 'Schaffhausen',
    'Schwyz': 'Schwyz',
    'Solothurn': 'St. Gallen',
    'St. Gallen': 'St. Gallen',
    'Thurgau': 'Thurgau',
    'Ticino': 'Ticino',
    'Uri': 'Uri',
    'Valais': 'Valais',
    'Vaud': 'Vaud',
    'Zug': 'Zug',
    'Roscommon': 'Roscommon',
    'Sligo': 'Sligo',
    'Tipperary': 'Tipperary',
    'Tyrone': 'Tyrone',
    'Waterford': 'Waterford',
    'WestValais': 'WestValais',
    'Wexford': 'Wexford',
    'Wicklow': 'Wicklow',

// Netherlands
    'Drenthe': 'Drenthe',
    'Flevoland': 'Flevoland',
    'Fryslan': 'Friesland',
    'Gelderland': 'Gelderland',
    'Groningen': 'Groningen',
    'Limburg': 'Limburg',
    'Noord-Brabant': 'North Brabant',
    'Noord-Holland': 'North Holland',
    'Oaveriessel': 'Overijssel',
    'Zuid-Holland': 'South Holland',
    'Utrecht': 'Utrecht',
    'Zeeland': 'Zeeland',

// Switzerland
    'Aargau': 'Aargau',
    'Appenzell Ausserrhoden': 'Appenzell Ausserrhoden',
    'Appenzell Innerrhoden': 'Appenzell Innerrhoden',
    'Basel-Landschaft': 'Basel-Landschaft',
    'Basel-Stadt': 'Basel-Stadt',
    'Bern': 'Bern',
    'Fribourg': 'Fribourg',
    'Geneva': 'Geneva',
    'Glarus': 'Glarus',
    'Graubünden': 'Graubünden',
    'Graubünddn': 'Graubünden',
    'Jura': 'Jura',
    'Luzern': 'Luzern',
    'Neuchâtel': 'Neuchâtel',
    'Nidwalden': 'Nidwalden',
    'Obwalden': 'Obwalden',
    'Schaffhausen': 'Schaffhausen',
    'Schwyz': 'Schwyz',
    'Solothurn': 'St. Gallen',
    'St. Gallen': 'St. Gallen',
    'Thurgau': 'Thurgau',
    'Ticino': 'Ticino',
    'Uri': 'Uri',
    'Valais': 'Valais',
    'Vaud': 'Vaud',
    'Zug': 'Zug',
    'Zürich': 'Zürich',
    'Kanton Zürich': 'Zürich',
    'ZH': 'Zürich',

// United Kingdom
    'England': 'England', // Both England and counties
    'Cheshire': 'England',
    'Essex': 'England',
    'London': 'England',
    'Norfolk': 'England',
    'South York': 'England',
    'Northern Ireland': 'Northern Ireland',
    'SCOTLAND': 'Scotland', // Not Showing
    'Wales': 'Wales',

// United States of America
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'IL': 'Illinois',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
};