module.exports = {

// Australia
    'AU-ACT': 'Australian Capital Territory',
    'ACT': 'Australian Capital Territory',
    'NSW': 'New South Wales',
    'New South Wales': 'New South Wales',
    'AU-NT': 'Northern Territory',
    'QLD': 'Queensland',
    'Queensland': 'Queensland',
    'SA': 'South Australia',
    'South Australia': 'South Australia',
    'TAS': 'Tasmania',
    'Tasmania': 'Tasmania',
    'VIC': 'Victoria',
    'Victoria': 'Victoria',
    'AU-WA': 'Western Australia', // Same Code as Washington
    'Western Australia': 'Western Australia',

// Austria
    'Burgenland': 'Burgenland',
    'Kärnten': 'Kärnten',
    'Niederösterreich': 'Niederösterreich',
    'Salzburg': 'Salzburg',
    'Steiermark': 'Steiermark',
    'Tirol': 'Tirol',
    'Oberösterreich': 'Oberösterreich',
    'Wien': 'Vienna',
    'Vorarlberg': 'Vorarlberg',


// Belgium
    'Antwerpen': 'Antwerpen',
    'Brabant wallon': 'Brabant wallon',
    'Bruxelles': 'Bruxelles',
    'Hainaut': 'Hainaut',
    'Liège': 'Liège',
    'Limburg': 'Limburg',
    'Luxembourg': 'Luxembourg',
    'Namur': 'Namur',
    'Oost-Vlaanderen': 'Oost-Vlaanderen',
    'West-Vlaanderen': 'West-Vlaanderen',
    'Vlaams-Brabant': 'Vlaams-Brabant',


// Brazil
    'Acre': 'Acre',
    'Alagoas': 'Alagoas',
    'Amapá': 'Amapá',
    'Amazonas': 'Amazonas',
    'Bahia': 'Bahia',
    'Ceará': 'Ceará',
    'Distrito Federal': 'Distrito Federal',
    'Espírito Santo': 'Espírito Santo',
    'Goiás': 'Goiás',
    'Maranhão': 'Maranhão',
    'Mato Grosso': 'Mato Grosso',
    'Mato Grosso do Sul': 'Mato Grosso do Sul',
    'Minas gerais': 'Minas Gerais',
    'Pará': 'Pará',
    'Paraíba': 'Paraíba',
    'Paraná': 'Paraná',
    'Pernambuco': 'Pernambuco',
    'Piauí': 'Piauí',
    'Rio de Janeiro': 'Rio de Janeiro',
    'Rio Grande do Norte': 'Rio Grande do Norte',
    'Rio Grande do Sul': 'Rio Grande do Sul',
    'Rondônia': 'Rondônia',
    'Roraima': 'Roraima',
    'Santa Catarina': 'Santa Catarina',
    'São Paulo': 'São Paulo',
    'Sergipe': 'Sergipe',
    'Tocantins': 'Tocantins',


// Canada
    'AB': 'Alberta',
    'BC': 'British Columbia',
    'MB': 'Manitoba',
    'NB': 'New Brunswick',
    'NL': 'Newfoundland and Labrador',
    'NT': 'Northwest Territories',
    'NS': 'Nova Scotia',
    'NU': 'Nunavut',
    'ON': 'Ontario',
    'PEI': 'Prince Edward Island',
    'QC': 'Quebec',
    'SK': 'Saskatchewan',
    'YU': 'Yukon',

// France
    'Auvergne-Rhône-Alpes': 'Auvergne-Rhône-Alpes',
    'Auvergne': 'Auvergne-Rhône-Alpes',
    'Rhône-Alpes': 'Auvergne-Rhône-Alpes',
    'Bourgogne-Franche-Comté': 'Bourgogne-Franche-Comté',
    'Bretagne': 'Bretagne',
    'Centre-Val de Loire': 'Centre-Val de Loire',
    'Corse': 'Corse',
    'Grand Est': 'Grand Est',
    'Guadeloupe': 'Guadeloupe',
    'Guyane': 'Guyane',
    'Île-de-France': 'Île-de-France',
    'La Réunion': 'La Réunion',
    'Martinique': 'Martinique',
    'Uritte': 'Uritte',
    'Normandie': 'Normandie',
    'Nouvelle-Aquitaine': 'Nouvelle-Aquitaine',
    'Aquitaine': 'Nouvelle-Aquitaine',
    'Occitanie': 'Occitanie',
    'Pays de la Loire': 'Pays de la Loire',
    'Île-de-France': 'Île-de-France',
    'Provence-Alpes-Côte d\'Azur': 'Provence-Alpes-Côte d\'Azur',
    'Marne': 'Grand Est',

// Germany
    'BW': 'Baden-Württemberg',
    'Baden-Württemberg': 'Baden-Württemberg',
    'BY': 'Bayern',
    'Bayern': 'Bayern',
    'BE': 'Berlin',
    'BER': 'Berlin',
    'Berlin': 'Berlin',
    'BB': 'Brandenburg',
    'Brandenburg': 'Brandenburg',
    'HB': 'Bremen',
    'Bremen': 'Bremen',
    'HH': 'Hamburg',
    'Hamburg': 'Hamburg',
    'HE': 'Hessen',
    'Hessen': 'Hessen',
    'NI': 'Niedersachsen',
    'Niedersachsen': 'Niedersachsen',
    'MV': 'Mecklenburg-Vorpommern',
    'Mecklenburg-Vorpommern': 'Mecklenburg-Vorpommern',
    'NW': 'Nordrhein-Westfalen',
    'Nordrhein-Westfalen': 'Nordrhein-Westfalen',
    'RP': 'Rheinland-Pfalz',
    'Rheinland-Pfalz': 'Rheinland-Pfalz',
    'RHEINLANDPFALZ': 'Rheinland-Pfalz',
    'SL': 'Saarland',
    'Saarland': 'Saarland',
    'SN': 'Sachsen',
    'Sachsen': 'Sachsen',
    'ST': 'Sachsen-Anhalt',
    'Sachsen-Anhalt': 'Sachsen-Anhalt',
    'TH': 'Thüringen',
    'Thüringen': 'Thüringen',

// Greece
    'Attica': 'Attica',
    'Athens': 'Attica',
    'Central Greece': 'Central Greece',
    'Central Macedonia': 'Central Macedonia',
    'Crete': 'Crete',
    'Berlin': 'Berlin',
    'Eastern Macedonia and Thrace': 'Eastern Macedonia and Thrace',
    'Epirus': 'Epirus',
    'Ionian Islands': 'Ionian Islands',
    'North Aegean': 'North Aegean',
    'Peloponnese': 'Peloponnese',
    'South Aegean': 'South Aegean',
    'Thessaly': 'Thessaly',
    'Western Greece': 'Western Greece',
    'Western Macedonia': 'Western Macedonia',

// Hong Kong
    'Hong Kong Island': 'Hong Kong',

// Hungary
    'Bács-Kiskun': 'Bács-Kiskun',
    'Baranya': 'Baranya',
    'Békés': 'Békés',
    'Borsod-Abaúj-Zemplén': 'Borsod-Abaúj-Zemplén',
    'Budapest': 'Budapest',
    'Csongrád': 'Csongrád',
    'Fejér': 'Fejér',
    'Győr-Moson-Sopron': 'Győr-Moson-Sopron',
    'Hajdú-Bihar': 'Hajdú-Bihar',
    'Heves': 'Heves',
    'Jász-Nagykun-Szolnok': 'Jász-Nagykun-Szolnok',
    'Komárom-Esztergom': 'Komárom-Esztergom',
    'Nógrád': 'Nógrád',
    'Pest': 'Pest',
    'Somogy': 'Somogy',
    'Szabolcs-Szatmár-Bereg': 'Szabolcs-Szatmár-Bereg',
    'Tolna': 'Tolna',
    'Vas': 'Vas',
    'Veszprém': 'Veszprém',
    'Zala': 'Zala',

// Ireland
    'Carlow': 'Carlow',
    'Cavan': 'Cavan',
    'Clare': 'Clare',
    'Cork': 'Cork',
    'Donegal': 'Donegal',
    'Dublin': 'Dublin',
    'Galway': 'Galway',
    'Kerry': 'Kerry',
    'Kildare': 'Kildare',
    'Kilkenny': 'Kilkenny',
    'Laois': 'Laois',
    'Leitrim': 'Leitrim',
    'Limerick': 'Limerick',
    'Longford': 'Longford',
    'Louth': 'Louth',
    'Mayo': 'Mayo',
    'Meath': 'Meath',
    'Monaghan': 'Monaghan',
    'Offaly': 'Offaly',
    'Roscommon': 'Roscommon',
    'Sligo': 'Sligo',
    'Tipperary': 'Tipperary',
    'Waterford': 'Waterford',
    'Westmeath': 'Westmeath',
    'WH': 'Westmeath',
    'Wexford': 'Wexford',
    'Wicklow': 'Wicklow',


// Italy
    'Abruzzo': 'Abruzzo',
    'Aosta Valley': 'Aosta Valley',
    'Valle d\'Aosta': 'Aosta Valley',
    'Apulia': 'Apulia',
    'Puglia': 'Apulia',
    'Basilicata': 'Basilicata',
    'Calabria': 'Calabria',
    'Campania': 'Campania',
    'Emilia-Romagna': 'Emilia-Romagna',
    'Friuli-Venezia-Giulia': 'Friuli-Venezia-Giulia',
    'Lazio': 'Lazio',
    'Liguria': 'Laguria',
    'Lombardy': 'Lombardy',
    'Lombardia': 'Lombardy',
    'Marche': 'Marche',
    'Molise': 'Molise',
    'Piedmont': 'Piedmont',
    'Peimonte': 'Piedmont',
    'Sardinia': 'Sardinia',
    'Sardegna': 'Sardinia',
    'Sicily': 'Sicily',
    'Sicilia': 'Sicily',
    'Trentino-South Tyrol': 'Trentino-South Tyrol',
    'Trentino-Alto Adige': 'Trentino-South Tyrol',
    'Tuscany': 'Tuscany',
    'Toscana': 'Tuscany',
    'Umbria': 'Umbria',
    'Veneto': 'Veneto',


// Netherlands
    'Drenthe': 'Drenthe',
    'Flevoland': 'Flevoland',
    'Fryslan': 'Friesland',
    'Friesland': 'Friesland',
    'Gelderland': 'Gelderland',
    'Groningen': 'Groningen',
    'Limburg': 'Limburg',
    'Noord-Brabant': 'North Brabant',
    'North Brabant': 'North Brabant',
    'Noord-Holland': 'North Holland',
    'North Holland': 'North Holland',
    'Oaveriessel': 'Overijssel',
    'Overijssel': 'Overijssel',
    'Zuid-Holland': 'South Holland',
    'South Holland': 'South Holland',
    'Utrecht': 'Utrecht',
    'Zeeland': 'Zeeland',

// Switzerland
    'Aargau': 'Aargau',
    'Appenzell Ausserrhoden': 'Appenzell Ausserrhoden',
    'Appenzell Innerrhoden': 'Appenzell Innerrhoden',
    'Basel-Landschaft': 'Basel-Landschaft',
    'Basel-Stadt': 'Basel-Stadt',
    'Bern': 'Bern',
    'Fribourg': 'Fribourg',
    'Geneva': 'Geneva',
    'Glarus': 'Glarus',
    'Graubünden': 'Graubünden',
    'Graubünddn': 'Graubünden',
    'Jura': 'Jura',
    'Luzern': 'Luzern',
    'Neuchâtel': 'Neuchâtel',
    'Nidwalden': 'Nidwalden',
    'Obwalden': 'Obwalden',
    'Schaffhausen': 'Schaffhausen',
    'Schwyz': 'Schwyz',
    'Solothurn': 'St. Gallen',
    'St. Gallen': 'St. Gallen',
    'Thurgau': 'Thurgau',
    'Ticino': 'Ticino',
    'Uri': 'Uri',
    'Valais': 'Valais',
    'Vaud': 'Vaud',
    'Zug': 'Zug',
    'Zürich': 'Zürich',
    'Kanton Zürich': 'Zürich',
    'ZH': 'Zürich',

// United Kingdom
    'England': 'England', // Both England and counties
    'Buckinghamshire': 'England',
    'Bucks': 'England',
    'Cheshire': 'England',
    'Essex': 'England',
    'London': 'England',
    'Middlesex': 'England',
    'Norfolk': 'England',
    'South York': 'England',
    'Surrey': 'England',
    'Northern Ireland': 'Northern Ireland',
    'SCOTLAND': 'Scotland', // Not Showing
    'Wales': 'Wales',

// United States of America
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'IL': 'Illinois',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
};