module.exports = {

// Australia
    'AU-ACT': 'Australian Capital Territory',
    'ACT': 'Australian Capital Territory',
    'NSW': 'New South Wales',
    'AU-NT': 'Northern Territory',
    'QLD': 'Queensland',
    'Queensland': 'Queensland',
    'SA': 'South Australia',
    'TAS': 'Tasmania',
    'VIC': 'Victoria',
    'Victoria': 'Victoria',
    'AU-WA': 'Western Australia', // Same Code as Washington

// Austria
    'Burgenland': 'Burgenland',
    'Kärnten': 'Kärnten',
    'Niederösterreich': 'Niederösterreich',
    'Salzburg': 'Salzburg',
    'Steiermark': 'Steiermark',
    'Tirol': 'Tirol',
    'Oberösterreich': 'Oberösterreich',
    'wien ': 'Vienna',
    'Vorarlberg': 'Vorarlberg',


// Canada
    'AB': 'Alberta',
    'BC': 'British Columbia',
    'MB': 'Manitoba',
    'NB': 'New Brunswick',
    'NL': 'Newfoundland and Labrador',
    'NT': 'Northwest Territories',
    'NS': 'Nova Scotia',
    'NU': 'Nunavut',
    'ON': 'Ontario',
    'PEI': 'Prince Edward Island',
    'QC': 'Quebec',
    'SK': 'Saskatchewan',
    'YU': 'Yukon',

// Canada
    'Auvergne-Rhône-Alpes': 'Auvergne-Rhône-Alpes',
    'Bourgogne-Franche-Comté': 'Bourgogne-Franche-Comté',
    'Bretagne': 'Bretagne',
    'Centre-Val de Loire': 'Centre-Val de Loire',
    'Corse': 'Corse',
    'Grand Est': 'Grand Est',
    'Guadeloupe': 'Guadeloupe',
    'Guyane': 'Guyane',
    'Île-de-France': 'Île-de-France',
    'La Réunion': 'La Réunion',
    'Martinique': 'Martinique',
    'Mayotte': 'Mayotte',
    'Normandie': 'Normandie',
    'Nouvelle-Aquitaine': 'Nouvelle-Aquitaine',
    'Occitanie': 'Occitanie',
    'Pays de la Loire': 'Pays de la Loire',
    'Île-de-France': 'Île-de-France',
    'Provence-Alpes-Côte d\'Azur ': 'Provence-Alpes-Côte d\'Azur',

// Germany
    'BW': 'Baden-Württemberg',
    'Baden-WÃ¼rttemberg': 'Baden-Württemberg',
    'BY': 'Bayern',
    'BE': 'Berlin',
    'Berlin': 'Berlin',
    'BB': 'Brandenburg',
    'HB': 'Bremen',
    'HH': 'Hamburg',
    'HE': 'Hessen',
    'NI': 'Niedersachsen',
    'MV': 'Mecklenburg-Vorpommern',
    'NW': 'Nordrhein-Westfalen',
    'RP': 'Rheinland-Pfalz',
    'SL': 'Saarland',
    'SN': 'Sachsen',
    'ST': 'Sachsen-Anhalt',

// Germany
    'BW': 'Baden-Württemberg',
    'Baden-Württemberg': 'Baden-Württemberg',
    'BY': 'Bayern',
    'BE': 'Berlin',
    'Berlin': 'Berlin',
    'BB': 'Brandenburg',
    'HB': 'Bremen',
    'HH': 'Hamburg',
    'HE': 'Hessen',
    'NI': 'Niedersachsen',
    'MV': 'Mecklenburg-Vorpommern',
    'NW': 'Nordrhein-Westfalen',
    'RP': 'Rheinland-Pfalz',
    'SL': 'Saarland',
    'SN': 'Sachsen',
    'ST': 'Sachsen-Anhalt',

// Ireland
    'Antrim': 'Antrim',
    'Armagh': 'Armagh',
    'Carlow': 'Carlow',
    'Cavan': 'Cavan',
    'Clare': 'Clare',
    'Cork': 'Cork',
    'Donegal': 'Donegal',
    'Down': 'Down',
    'Dublin': 'Dublin',
    'Fermanagh': 'Fermanagh',
    'Galway': 'Galway',
    'Kerry': 'Kerry',
    'Kildare': 'Kildare',
    'Kilkenny': 'Kilkenny',
    'Laois': 'Laois',
    'Leitrim': 'Leitrim',
    'Limerick': 'Limerick',
    'Londonderry': 'Derry',
    'Derry': 'Derry',
    'Longford': 'Longford',
    'Louth': 'Louth',
    'Mayo': 'Mayo',
    'Meath': 'Meath',
    'Monaghan': 'Monaghan',
    'Offaly': 'Offaly',
    'Roscommon': 'Roscommon',
    'Sligo': 'Sligo',
    'Tipperary': 'Tipperary',
    'Tyrone': 'Tyrone',
    'Waterford': 'Waterford',
    'Westmeath': 'Westmeath',
    'Wexford': 'Wexford',
    'Wicklow': 'Wicklow',

// Netherlands
    'Drenthe': 'Drenthe',
    'Flevoland': 'Flevoland',
    'Fryslan': 'Friesland',
    'Gelderland': 'Gelderland',
    'Groningen': 'Groningen',
    'Limburg': 'Limburg',
    'Noord-Brabant': 'North Brabant',
    'Noord-Holland': 'North Holland',
    'Oaveriessel': 'Overijssel',
    'Zuid-Holland': 'South Holland',
    'Utrecht': 'Utrecht',
    'Zeeland': 'Zeeland',

// United Kingdom
    'England': 'England', // Both England and counties
    'Cheshire': 'England',
    'Essex': 'England',
    'Norfolk': 'England',
    'South York': 'England',
    'Northern Ireland': 'Northern Ireland',
    'Scotland': 'Scotland', // Not Showing
    'Wales': 'Wales',

// United States of America
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'IL': 'Illinois',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
};