module.exports = {

// Australia
    'AU-ACT': 'Asutralian Capital Territory',
    'NSW': 'New South Wales',
    'AU-NT': 'Northern Territory',
    'QLD': 'Queensland',
    'Queensland': 'Queensland',
    'SA': 'South Australia',
    'TAS': 'Tasmania',
    'VIC': 'Victoria',
    'Victoria': 'Victoria',
    'WA': 'Western Australia', // Same Code as Washington

// Austria
    'Burgenland': 'Burgenland',
    'Kärnten': 'Kärnten',
    'Niederösterreich': 'Niederösterreich',
    'Salzburg': 'Salzburg',
    'Steiermark': 'Steiermark',
    'Tirol': 'Tirol',
    'Oberösterreich': 'Oberösterreich',
    'wien': 'wien',
    'Vorarlberg': 'Vorarlberg',


// Canada
    'AB': 'Alberta',
    'BC': 'British Columbia',
    'MB': 'Manitoba',
    'NB': 'New Brunswick',
    'NL': 'Newfoundland and Labrador',
    'NT': 'Northwest Territories',
    'NS': 'Nova Scotia',
    'NU': 'Nunavut',
    'ON': 'Ontario',
    'PEI': 'Prince Edward Island',
    'QC': 'Quebec',
    'SK': 'Saskatchewan',
    'YU': 'Yukon',

// Germany
    'BW': 'Baden-Württemberg',
    'Baden-Württemberg': 'Baden-Württemberg',
    'BY': 'Bayern',
    'BE': 'Berlin',
    'Berlin': 'Berlin',
    'BB': 'Brandenburg',
    'HB': 'Bremen',
    'HH': 'Hamburg',
    'HE': 'Hessen',
    'NI': 'Niedersachsen',
    'MV': 'Mecklenburg-Vorpommern',
    'NW': 'Nordrhein-Westfalen',
    'RP': 'Rheinland-Pfalz',
    'SL': 'Saarland',
    'SN': 'Sachsen',
    'ST': 'Sachsen-Anhalt',


// United Kingdom
    'England': 'England', // Both England and counties
    'Cheshire': 'England',
    'Essex': 'England',
    'Norfolk': 'England',
    'South York': 'England',
    'Northern Ireland': 'Northern Ireland',
    'Scotland': 'Scotland', // Not Showing
    'Wales': 'Wales',

// United States of America
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'IL': 'Illinois',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RH': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',
};